name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  php-playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          extensions: ast
      - run: echo $PWD
      - run: ls -la
      - run: php -v
  my_first_docker_job:
    runs: docker
    steps:
      - name: My first step
        uses: docker://alpine:3.8

